name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  javabuild:
    name: Java Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Build
        run: mvn -B package
  cbuild:
    needs: javabuild
    name: C Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Build
        run: |
          cd learn-lex-yacc-c
          sudo pt-get update -qq
          sudo apt-get install -y bison flex
          autoreconf --install
          ./configure
          make 
          make check
