name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  javabuild:
    name: Java Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Build
        run: mvn -B package
  cbuild:
    needs: javabuild
    name: C Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Build
        run: |
          cd learn-lex-yacc-c
          sudo apt-get update -qq
          sudo apt-get install -y bison flex
          autoreconf --install
          ./configure
          make 
          make check
